export class Product {
  constructor(
    public CombinationDescription: string,
    public CreateDate: string,
    public DescriptionInSite_En: string,
    public DescriptionInSite_Fa: string,
    public GeneratedCode: string,
    public IDDefineDetailProduct: string,
    public IDMadeCountry: string,
    public IDUnit: string,
    public IDUser: string,
    public IDX: number,
    public IndexDescriptionPicUrl: string,
    public IndexDescriptionText: string,
    public LegalMenuPicUrl: string,
    public LegalName_En: string,
    public MadeCountryTitle: string,
    public MetaDescription: string,
    public MetaTag: string,
    public PartNumber: string,
    public PicUrl: string,
    public ProductIndexDescriptionText: string,
    public ProductName_En: string,
    public ShortTechnicalDescription: string,
    public ShowInSite: boolean,
    public Sort: number,
    public SpecialDefine: boolean,
    public TechnicalDescription: string,
    public UnderSpot: boolean
  ) { }
}